version:  '3'

services: 
  db:
    image: mariadb:latest
    restart: always
    env_file: 
      - .env

  yuki-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "3000:3000"
    env_file: 
      - .env
    environment: 
      MYSQL_ADDRESS: db